---
- name: Ansible to OpenShift Integration
  hosts: localhost
  gather_facts: false
  #ignore_errors: true
  collections:
    - community.general
  vars:
    #ocp_host_api: https://api.cluster-rclxq.rclxq.sandbox1046.opentlc.com:6443
    #ocp_user_name: kubeadmin
    #ocp_password: xxxxx
    ocp_host_api: "{{ lookup('ansible.builtin.env', 'OPENSHIFT_HOST_API') }}"
    ocp_user_name: "{{ lookup('ansible.builtin.env', 'OPENSHIFT_LOGIN_USERNAME') }}"
    ocp_password: "{{ lookup('ansible.builtin.env', 'OPENSHIFT_LOGIN_PASSWORD') }}"
    # getting ocp_namespace from Survey form
    # ocp_namespace: openshift-console 
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Log in to OCP to obtain access token
      redhat.openshift.openshift_auth:
        host: "{{ ocp_host_api }}"
        username: "{{ ocp_user_name }}"
        password: "{{ ocp_password }}"
        validate_certs: false
      register: openshift_auth_results

    - name: Get a list of all pods from a OCP namespace
      kubernetes.core.k8s_info:
        host: "{{ ocp_host_api }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        kind: Pod
        namespace: "{{ ocp_namespace }}"
        validate_certs: false
      register: change_output
        
    - name: Format pods list as CSV
      ansible.builtin.set_fact:
        pods_csv: "{{ pods_csv | default('') }}{{ item.metadata.name }},{{ item.status.containerStatuses[0].ready }},{{ item.status.containerStatuses[0].restartCount }},{{ item.metadata.creationTimestamp }}\n"
      loop: "{{ change_output.resources }}"
      ignore_errors: true

    - name: Print pods list as CSV
      ansible.builtin.debug:
        msg: "{{ pods_csv | to_nice_csv }}"
      ignore_errors: true

    - name: Write output to a csv file
      ansible.builtin.copy:
        content: "{{ pods_csv | to_nice_csv }}"
        dest: /tmp/pod_list_1.csv
      ignore_errors: true
  
    - name: Print details
      ansible.builtin.debug:
        msg: "{{ change_output.resources | map(attribute='metadata.name') | join(', ') }}"
      ignore_errors: true

    - name: Print pod list in CSV table format
      ansible.builtin.debug:
        msg: "{{ change_output | community.general.json_query('resources[*].{name: metadata.name, namespace: metadata.namespace, status: status.phase}') | map('join', ',') | join(' ') }}"
      ignore_errors: true

    - name: Print pod list in table format
      ansible.builtin.debug:
        msg: "{{ change_output | to_nice_yaml }}"

    - name: Write output to a csv file with pod name, number of running instances, running status, restarts, age
      ansible.builtin.copy:
        content: "{{ change_output | community.general.json_query('resources[*].{name: metadata.name, running_instances: status.containerStatuses[*].ready, running_status: status.containerStatuses[*].state.running, restarts: status.containerStatuses[*].restartCount, age: metadata.creationTimestamp}') | to_nice_csv }}"
        dest: /tmp/pod_list_2.csv
      ignore_errors: true
...
